SELECT r.CAR_ID, r.CAR_TYPE, 
    ROUND(r.DAILY_FEE * 30 * (100-d.DISCOUNT_RATE)/100) AS FEE
FROM CAR_RENTAL_COMPANY_CAR r
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN d
    ON d.CAR_TYPE=r.CAR_TYPE
    AND d.DURATION_TYPE='30일 이상'
WHERE r.CAR_TYPE IN ('세단', 'SUV')
    AND r.CAR_ID NOT IN (
        SELECT h.CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY h
        WHERE h.START_DATE<='2022-11-30' AND h.END_DATE>='2022-11-01'
)
HAVING FEE>=500000 AND FEE<2000000
ORDER BY FEE DESC, r.CAR_TYPE, r.CAR_ID DESC