-- 코드를 작성해주세요
select 
    RANKED_DATA.ID,
    CASE
        WHEN P_RANK <=0.25 THEN 'CRITICAL'
        WHEN P_RANK <=0.50 THEN 'HIGH'
        WHEN P_RANK <=0.75 THEN 'MEDIUM'
        ELSE 'LOW'
    END AS COLONY_NAME
FROM(
    SELECT
        ID,
        PERCENT_RANK() OVER (ORDER BY SIZE_OF_COLONY DESC) AS P_RANK
    FROM ECOLI_DATA
) AS RANKED_DATA #서브쿼리 이름 지정 필요
ORDER BY RANKED_DATA.ID;
