-- 코드를 입력하세요
SELECT 
    MONTH(c.START_DATE) AS MONTH, c.CAR_ID, COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY c
WHERE
    c.START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
    AND c.CAR_ID IN(
        SELECT r.CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY r
        where r.START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
        GROUP BY r.CAR_ID
        HAVING COUNT(*)>=5
    )
GROUP BY MONTH(c.START_DATE), c.CAR_ID
ORDER BY MONTH ASC, c.CAR_ID DESC

# ORDER BY 절은 SQL의 실행 순서상 가장 마지막에 실행되기 때문에
# SELECT 절에서 정의한 별칭(Alias)을 그대로 가져다 쓸 수 있다
   
