SELECT m.MEMBER_NAME, r.REVIEW_TEXT, r.REVIEW_DATE
FROM MEMBER_PROFILE m
LEFT JOIN REST_REVIEW r ON m.MEMBER_ID=r.MEMBER_ID
WHERE m.MEMBER_ID=(
    SELECT MEMBER_ID
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    ORDER BY COUNT(*) DESC
    LIMIT 1
)
ORDER BY r.REVIEW_DATE ASC, r.REVIEW_TEXT ASC