SELECT 
    b.AUTHOR_ID, 
    a.AUTHOR_NAME,
    b.CATEGORY,
    SUM(b.PRICE*s.SALES) AS TOTAL_SALES
FROM BOOK b
JOIN AUTHOR a 
    ON b.AUTHOR_ID=a.AUTHOR_ID
JOIN (
    SELECT s.BOOK_ID, SUM(SALES) AS SALES
    FROM BOOK_SALES s
    WHERE '2022-01-01'<= s.SALES_DATE
        AND '2022-01-31'>= s.SALES_DATE
    GROUP BY s.BOOK_ID
) AS s
    ON b.BOOK_ID=s.BOOK_ID
GROUP BY b.AUTHOR_ID, a.AUTHOR_NAME, b.CATEGORY
ORDER BY b.AUTHOR_ID, b.CATEGORY DESC